---
- name: Install Trove packages
  block:
    - name: Install Trove packages
      apt:
        name:
          - trove-api
          - trove-taskmanager
          - trove-conductor
          - python3-troveclient
        state: present
  rescue:
    - name: Log Trove package installation failure
      debug:
        msg: "Failed to install Trove packages. Check your package manager logs."

- name: Configure Trove database connection
  block:
    - name: Configure Trove database connection
      lineinfile:
        path: /etc/trove/trove.conf
        section: database
        option: connection
        value: "mysql+pymysql://{{ trove_db_user }}:{{ trove_db_password }}@{{ trove_db_host }}/{{ trove_db_name }}"
  rescue:
    - name: Log Trove database configuration failure
      debug:
        msg: "Failed to configure Trove database connection."

- name: Configure Keystone authentication for Trove
  block:
    - name: Configure Keystone authentication for Trove
      lineinfile:
        path: /etc/trove/trove.conf
        section: keystone_authtoken
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { option: "auth_url", value: "http://{{ keystone_host }}:5000/v3" }
        - { option: "memcached_servers", value: "127.0.0.1:11211" }
        - { option: "auth_type", value: "password" }
        - { option: "project_domain_name", value: "Default" }
        - { option: "user_domain_name", value: "Default" }
        - { option: "project_name", value: "service" }
        - { option: "username", value: "trove" }
        - { option: "password", value: "{{ trove_service_password }}" }
  rescue:
    - name: Log Keystone authentication configuration failure
      debug:
        msg: "Failed to configure Keystone authentication for Trove."

- name: Initialize Trove database
  block:
    - name: Initialize Trove database
      command: >
        su -s /bin/sh -c "trove-manage db_sync" trove
      args:
        creates: /var/lib/trove/trove.sqlite
  rescue:
    - name: Rollback Trove database initialization
      command: >
        mysql -u root -e "DROP DATABASE IF EXISTS {{ trove_db_name }};"
      ignore_errors: true

- name: Restart Trove services
  block:
    - name: Restart Trove services
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      with_items:
        - trove-api
        - trove-taskmanager
        - trove-conductor
  rescue:
    - name: Log Trove service restart failure
      debug:
        msg: "Failed to restart Trove services."