# EC2 public IP for binding services
ec2_public_ip: <EC2_PUBLIC_IP>

# LVM configuration for Cinder
cinder_volume_devices:
  - /dev/sdb
  - /dev/sdc
cinder_volume_group: cinder-volumes

# keystione configuration
region_name: RegionOne
keystone_host: "{{ ec2_public_ip }}"

# Swift storage configuration
swift_storage_devices:
  - /srv/node/sdd
  - /srv/node/sde
swift_bind_port: 8080